name: Aaqa Ishtyaq - Python developer
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
kramdown:
    input: GFM
    syntax_highlighter: rouge
permalink: /notes/:title
baseurl: /
